logging:
  level:
    org:
      atmosphere: warn
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml


# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
